import io
import os
from typing import List, Dict, Any

import requests
from PIL import Image
from fastapi import FastAPI, File, UploadFile, HTTPException
from fastapi.responses import HTMLResponse
from fastapi.staticfiles import StaticFiles

app = FastAPI(title="Orbital Verify")

app.mount("/static", StaticFiles(directory="static"), name="static")

MAX_BYTES = 12 * 1024 * 1024

@app.get("/", response_class=HTMLResponse)
def home():
    with open("static/index.html", "r", encoding="utf-8") as f:
        return f.read()

def ai_score_from_huggingface(image_bytes: bytes) -> Dict[str, Any]:
    """
    Uses Hugging Face Inference API if configured.

    Set:
      HF_API_TOKEN=...
      HF_MODEL_ID=<an image-classification model that distinguishes AI vs real>

    IMPORTANT:
    Different models use different label names. Adjust AI_LABELS / REAL_LABELS
    below to match your chosen detector model.
    """
    token = os.getenv("HF_API_TOKEN")
    model_id = os.getenv("HF_MODEL_ID")

    if not token or not model_id:
        # Development fallback only. It deliberately returns an uncertain result
        # instead of pretending to detect AI without a model.
        return {
            "probability": 0.50,
            "source": "fallback",
            "note": "No AI detector model is configured, so this is a neutral demo score."
        }

    url = f"https://api-inference.huggingface.co/models/{model_id}"
    headers = {"Authorization": f"Bearer {token}"}
    r = requests.post(url, headers=headers, data=image_bytes, timeout=45)
    if not r.ok:
        raise RuntimeError(f"Detector API error: {r.status_code}")

    output = r.json()
    if isinstance(output, list) and output and isinstance(output[0], list):
        output = output[0]

    AI_LABELS = {"ai", "artificial", "generated", "fake", "synthetic"}
    REAL_LABELS = {"real", "human", "photo", "natural"}

    ai_prob = 0.0
    real_prob = 0.0

    for item in output if isinstance(output, list) else []:
        label = str(item.get("label", "")).lower()
        score = float(item.get("score", 0))
        if any(k in label for k in AI_LABELS):
            ai_prob = max(ai_prob, score)
        if any(k in label for k in REAL_LABELS):
            real_prob = max(real_prob, score)

    if ai_prob == 0 and real_prob > 0:
        ai_prob = max(0.0, 1.0 - real_prob)
    if ai_prob == 0 and real_prob == 0:
        raise RuntimeError("Could not map model labels. Adjust AI_LABELS/REAL_LABELS.")

    return {
        "probability": min(max(ai_prob, 0.0), 1.0),
        "source": model_id,
        "note": "Probability is produced by the configured image-classification model."
    }

def web_similar_images(image_bytes: bytes, filename: str) -> List[Dict[str, str]]:
    """
    Optional reverse/similar-image search hook.

    This starter project leaves the provider pluggable because 'search the whole
    internet' is not realistically possible from a normal app, and providers have
    different contracts.

    Recommended production options:
    - Google Cloud Vision Web Detection
    - TinEye API
    - a licensed visual-search provider

    Implement one provider here and return:
    [
      {
        "title": "...",
        "thumbnail": "https://...",
        "image_url": "https://...",
        "source_url": "https://...",
        "source": "..."
      }
    ]
    """
    return []

def verdict_for(prob: float, web_search_ran: bool, matches_found: bool) -> str:
    """
    Display logic requested for the UI:
    - Rounded detector score = 100% -> "AI generated"
    - 40% to 99% -> "Might be AI generated"
    - Below 40% + a completed web search with no matches ->
      "Photo not found on open internet nor generated by AI"
    - Below 40% + web matches -> "Likely not AI generated"
    - Below 40% without a configured web-search provider ->
      "Likely not AI generated"
    """
    pct = round(prob * 100)

    if pct == 100:
        return "AI generated"

    if pct >= 40:
        return "Might be AI generated"

    if web_search_ran and not matches_found:
        return "Photo not found on open internet nor generated by AI"

    return "Likely not AI generated"


@app.post("/api/analyze")
async def analyze(file: UploadFile = File(...)):
    content_type = file.content_type or ""

    if content_type.startswith("video/"):
        raise HTTPException(status_code=415, detail="Video input is not available right now.")
    if not content_type.startswith("image/"):
        raise HTTPException(status_code=415, detail="Please upload an image file.")

    image_bytes = await file.read()
    if len(image_bytes) > MAX_BYTES:
        raise HTTPException(status_code=413, detail="Image exceeds the 12 MB limit.")

    try:
        Image.open(io.BytesIO(image_bytes)).verify()
    except Exception:
        raise HTTPException(status_code=400, detail="The uploaded file is not a valid image.")

    try:
        detector = ai_score_from_huggingface(image_bytes)
    except Exception as e:
        raise HTTPException(status_code=502, detail=str(e))

    probability = float(detector["probability"])

    # The starter web_similar_images() function is only a placeholder until you
    # connect a real reverse-image / web-visual-search provider.
    #
    # Set WEB_IMAGE_SEARCH_ENABLED=true only after implementing that provider.
    web_search_ran = os.getenv("WEB_IMAGE_SEARCH_ENABLED", "false").lower() == "true"

    matches = []
    if web_search_ran:
        matches = web_similar_images(image_bytes, file.filename or "upload")

    pct = round(probability * 100)

    if pct == 100:
        explanation = (
            "Detector score: 100%. The model returned its maximum AI-generation "
            "confidence. This is still a model result, not mathematical proof of origin."
        )
    elif pct >= 40:
        explanation = (
            f"Detector score: {pct}%. The image has enough AI-like visual signals "
            "to be flagged as possibly AI generated."
        )
    elif web_search_ran and not matches:
        explanation = (
            f"Detector score: {pct}%. The detector is below the 40% AI threshold, "
            "and the configured public-web image search returned no similar matches."
        )
    elif matches:
        explanation = (
            f"Detector score: {pct}%. The image is below the 40% AI threshold. "
            "Possible visually similar public-web images were found below."
        )
    else:
        explanation = (
            f"Detector score: {pct}%. The image is below the 40% AI threshold. "
            "Public-web similarity search is not configured yet."
        )

    return {
        "verdict": verdict_for(probability, web_search_ran, bool(matches)),
        "ai_probability": probability,
        "explanation": explanation,
        "similar_images": matches[:12],
        "web_search_enabled": web_search_ran,
        "stores_upload": False
    }
